export const ADD_SPECIES = "ADD_SPECIES";
export const REMOVE_SPECIES = "REMOVE_SPECIES";
export const SET_SPECIES = "SET_SPECIES";
export const SET_SIDES = "SET_SIDES";
export const SET_ORDERED = "SET_ORDERED";

export const PURCHASE_BOX_SUCCESS = "PURCHASE_BOX_SUCCESS";
export const PURCHASE_BOX_FAIL = "PURCHASE_BOX_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_DISPLAY_SUCESS = "FETCH_DISPLAY_SUCESS";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
